# aGENtrader v2 Secrets Configuration
# WARNING: Do not commit this file to version control

# External API Keys
coinapi_key: ""  # Replace with your CoinAPI.io API key

# Database Credentials (if using external database)
db_username: ""
db_password: ""